# Site settings
title: Junglebarry
email: david@junglebarry.com
work_email: david@whisk.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of David James Brooks.
  Likely to feature functional programming, scala, and natural language processing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junglebarry.com" # the base hostname & protocol for your site
twitter_username: junglebarry
github_username:  junglebarry

# Build settings
markdown: kramdown
